// Generated by https://quicktype.io

export interface IAuthResponse {
  type: string;
  error: null;
  url: string;
  params: Params;
  authentication: Authentication;
  errorCode: null;
}

interface Authentication {
  accessToken: string;
  tokenType: string;
  expiresIn: string;
  scope: string;
  state: string;
  issuedAt: number;
}

 interface Params {
  "exp://192.168.31.157:19000/--/expo-auth-session": string;
  state: string;
  access_token: string;
  token_type: string;
  expires_in: string;
  scope: string;
  authuser: string;
  prompt: string;
}
